name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          ssh user@backend-machine "bash -s" <<'EOF'
            cd /path/to/backend && git pull && php artisan migrate
          EOF
